// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/forum-overview.tsx": () => import("../components/mockups/forum-overview.tsx"),
  "./components/mockups/forum-thread.tsx": () => import("../components/mockups/forum-thread.tsx"),
  "./components/mockups/video.tsx": () => import("../components/mockups/video.tsx")
};
